sim_params:
  cosmo:
    flat: True
    H0: 67.2
    Om0: 0.3
    Ob0: 0.048
    sigma8: 0.8
    ns: 0.96
    w0: -1.0
    
  log10_Mstar0_theta_ej: 16.0


  theta_ej_0: 2.0
  nu_theta_ej_M: -0.33
  nu_theta_ej_z: -1.22
  
  log10_Mc0 : 10.75
  mu_beta : 0.0762

  # log10M1_fshmr: 12.35
  # log10M1_a_fshmr: 0.28
  # beta_fshmr: 0.44
  # beta_a_fshmr: 0.18
  # delta_fshmr: 0.57
  # delta_a_fshmr: 0.17
  # siglogMstar_Ncen: 0.25
  # alphasat_Nsat: 1.0


##### TEST1######
  # log10M1_fshmr: 12.42
  # log10M1_a_fshmr: -0.25
  # log10Mstar0_fshmr: 10.72
  # log10Mstar0_a_fshmr: 0.55
  # beta_fshmr: 0.4
  # beta_a_fshmr: 0.2
  # delta_fshmr: 0.41
  # delta_a_fshmr: -0.11
  # gamma_fshmr: 1.70
  # gamma_a_fshmr: -1.8
  # siglogMstar_Ncen: 0.5
  # alphasat_Nsat: 1.16
  # Bcut_Nsat: 1.69
  # Bsat_Nsat: 9.01
  # betacut_Nsat: 0.6
  # betasat_Nsat: 0.3


##### TEST2######
  log10M1_fshmr: 12.55
  log10M1_a_fshmr: 0.38
  log10Mstar0_fshmr: 10.72
  log10Mstar0_a_fshmr: 0.55
  beta_fshmr: 0.4
  beta_a_fshmr: 0.2
  delta_fshmr: 0.37
  delta_a_fshmr: 0.21
  gamma_fshmr: 1.79
  gamma_a_fshmr: -0.72
  siglogMstar_Ncen: 0.7
  alphasat_Nsat: 1.19
  Bcut_Nsat: 1.69
  Bsat_Nsat: 9.01
  betacut_Nsat: 0.6
  betasat_Nsat: 0.3



  # log10M1_fshmr: 12.0
  # log10M1_a_fshmr: 0.3
  # log10Mstar0_fshmr: 10.72
  # log10Mstar0_a_fshmr: 0.55
  # beta_fshmr: 0.4
  # beta_a_fshmr: 0.2
  # delta_fshmr: 0.12
  # delta_a_fshmr: 0.15
  # gamma_fshmr: 1.56
  # gamma_a_fshmr: 2.51
  # siglogMstar_Ncen: 0.25
  # alphasat_Nsat: 1.0
  # Bcut_Nsat: 1.69
  # Bsat_Nsat: 9.01
  # betacut_Nsat: 0.6
  # betasat_Nsat: 0.74


  alpha_nt : 0.05

halo_params:

  rmax: 16.0
  nr: 64


  conc_model: Diemer15
 
other_params:
  alpha_ky : 1.0
  A_IA : 0
  eta_IA : 0

analysis:
  num_points_trapz_int: 64
  model_galaxies: True
  beam_fwhm_arcmin: 1.6
  analysis_coords: fourier
  tSZ_transition_model : poweradd

  zmin_for_Cls: 0.01
  zmax_for_Cls: 1.6
  nz_for_Cls: 64

  # fsky_yy: 0.4
  # fsky_ky: 0.4
  # fsky_kk: 0.4
  # fsky_yg: 0.4
  # fsky_kg: 0.4
  # fsky_gg: 0.4

  # fsky_yy: 0.4
  # fsky_ky: 0.437
  # fsky_kk: 0.437
  # fsky_yg: 0.34
  # fsky_kg: 0.1
  # fsky_gg: 0.34

  fsky_yy: 0.4
  fsky_ky: 0.4
  fsky_kk: 0.4
  fsky_yg: 0.35
  fsky_kg: 0.35
  fsky_gg: 0.4

  sigma_epsilon_SN_bins:
    - 0.26
    - 0.26
    - 0.26
    - 0.26
    - 0.26
    - 0.26
  
  neff_arcmin2_SN_bins:
    - 4.64
    - 4.64
    - 4.64
    - 4.64
    - 4.64  
    - 4.64  

